server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/DDMonzonUrrutia/config-data-server.git
          searchPaths:
          username: ${GIT_USERNAME}
          password: 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
          default-label: "main"
  security:
    user:
      name: ${SECURITY_USERNAME}
      password: ${SECURITY_PASSWORD}